plugins {
    id 'com.android.application'
}

def signingProperties = new Properties()
def signingPropertiesFile = rootProject.file("keystore.properties")

if (signingPropertiesFile.exists()) {
    signingProperties.load(new FileInputStream(signingPropertiesFile))
}

android {
    namespace 'br.com.inforti.calceletrica'
    compileSdk 35

    defaultConfig {
        applicationId "br.com.inforti.calceletrica"
        minSdk 23
        targetSdk 35
        versionCode 41
        versionName "4.1.0"
    }

    signingConfigs {
        release {
            if (signingPropertiesFile.exists()) {
                storeFile file(signingProperties['storeFile'])
                storePassword signingProperties['storePassword']
                keyAlias signingProperties['keyAlias']
                keyPassword signingProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
