name: Gerar APK Calc-Eletrica

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK Android
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Configurar Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip
          echo "$PWD/gradle-8.7/bin" >> "$GITHUB_PATH"

      - name: Verificar projeto
        run: |
          gradle projects

      - name: Compilar APK Release
        run: |
          gradle --no-daemon assembleRelease

            - name: Localizar APK gerado
        run: |
          echo "Arquivos APK encontrados:"
          find app/build/outputs -type f -name "*.apk" -print

      - name: Disponibilizar APK Release
        uses: actions/upload-artifact@v4
        with:
          name: Calc-Eletrica-3.0.1-Release
          path: app/build/outputs/**/*.apk
          if-no-files-found: error
